"""
Test script for Tender CRUD operations
Requires: SUPABASE_URL and SUPABASE_KEY environment variables
"""
import os
import sys
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dto import TenderDTO, TenderAttachmentDTO, TenderSpecDTO, TenderSource, CVBasis
from repository import SupabaseRepository

# Supabase Credentials from environment
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY") or os.getenv("SUPABASE_ANON_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ValueError("Missing SUPABASE_URL or SUPABASE_KEY environment variables")

def test_tender_crud():
    print("=== Testing Tender CRUD ===")
    repo = SupabaseRepository(SUPABASE_URL, SUPABASE_KEY)
    
    # 1. Create a Tender Object
    tender = TenderDTO(
        bid_ntce_no="20241220001",
        bid_ntce_ord="00",
        source=TenderSource.G2B,
        bid_ntce_nm="Test Coal Tender 2024",
        ntce_div_cd="1",
        dminstt_nm="Korea Test Power",
        asign_bdgt_amt=1000000.00,
        bid_clse_dt=datetime.now(),
        ai_summary="This is a test summary generated by script.",
        relevance_score=0.95
    )
    
    # 2. Upsert Tender
    print(f"Upserting tender: {tender.bid_ntce_no}")
    result = repo.upsert_tender(tender)
    print(f"Upsert result ID: {result['id']}")
    tender_id = result['id']
    
    # 3. Validation
    fetched = repo.get_tender_by_id(tender_id)
    assert fetched['bid_ntce_no'] == "20241220001"
    assert fetched['source'] == "G2B"
    print("Tender verification successful!")
    
    # 4. Create Attachment
    print("\n=== Testing Attachment CRUD ===")
    attachment = TenderAttachmentDTO(
        tender_id=tender_id,
        file_name="spec_sheet.hwp",
        file_type="hwp",
        file_url="http://example.com/spec_sheet.hwp",
        extracted_text="Sample extracted text content."
    )
    
    # 5. Upsert Attachment
    att_result = repo.upsert_attachment(attachment)
    print(f"Attachment result ID: {att_result['id']}")
    
    # 6. Validation
    attachments = repo.get_attachments_by_tender_id(tender_id)
    assert len(attachments) >= 1
    assert attachments[0]['file_name'] == "spec_sheet.hwp"
    print("Attachment verification successful!")
    
    # 7. Update Tender (Upsert Check)
    print("\n=== Testing Update ===")
    tender.ai_summary = "Updated Summary"
    updated = repo.upsert_tender(tender)
    assert updated['id'] == tender_id # Should be same ID
    assert updated['ai_summary'] == "Updated Summary"
    print("Update verification successful!")
    
    # 8. Create Spec
    print("\n=== Testing Spec CRUD ===")
    spec = TenderSpecDTO(
        tender_id=tender_id,
        commodity_type="Thermal Coal",
        cv_min_kcal=6000,
        cv_max_kcal=None,
        cv_basis=CVBasis.NAR,
        sulfur_max_pct=1.0,
        ash_max_pct=15.0,
        quantity_mt=50000,
        origin="Australia",
        delivery_port="Incheon"
    )
    
    # 9. Upsert Spec
    spec_result = repo.upsert_tender_spec(spec)
    print(f"Spec result ID: {spec_result['id']}")
    
    # 10. Validation
    fetched_spec = repo.get_tender_spec_by_tender_id(tender_id)
    assert fetched_spec['cv_min_kcal'] == 6000
    assert fetched_spec['origin'] == "Australia"
    print("Spec verification successful!")

if __name__ == "__main__":
    try:
        test_tender_crud()
        print("\nAll Tests Passed!")
    except Exception as e:
        print(f"\nTests Failed: {e}")
        import traceback
        traceback.print_exc()
